#pragma once

#include "common/math/Math.hpp"
#include "sim/gnc/parameters/Parameter.hpp"

#include <array>
#include <cstddef>

namespace gnc {
enum class Px4TecsParameter : std::size_t {
  MinimumPitch,
  MaximumPitch,
  MinimumThrottle,
  MaximumThrottle,
  TrimThrottle,
  MinimumAirspeed,
  MaximumAirspeed,
  MaximumClimbRate,
  MaximumSinkRate,
  AltitudeErrorGain,
  AirspeedErrorGain,
  ThrottleDampingGain,
  ThrottleIntegralGain,
  PitchDampingGain,
  PitchIntegralGain,
  EnergyBalanceFeedForwardGain,
  TotalEnergyRateFilterTimeConstant,
  PitchSlewRate,
  ThrottleSlewRate,
  Count,
};

using Px4TecsParameterMetadata = ParameterMetadata<Px4TecsParameter>;

inline constexpr std::array<Px4TecsParameterMetadata,
    static_cast<std::size_t>(Px4TecsParameter::Count)>
    Px4TecsParameters{{
        {Px4TecsParameter::MinimumPitch,
            "FW_P_LIM_MIN",
            "Minimum pitch",
            UnitId::Radian,
            UnitId::Degree,
            math::DegToRad(-45.0),
            0.0,
            math::DegToRad(-10.0),
            math::DegToRad(0.45)},
        {Px4TecsParameter::MaximumPitch,
            "FW_P_LIM_MAX",
            "Maximum pitch",
            UnitId::Radian,
            UnitId::Degree,
            0.0,
            math::DegToRad(45.0),
            math::DegToRad(15.0),
            math::DegToRad(0.45)},
        {Px4TecsParameter::MinimumThrottle,
            "FW_THR_MIN",
            "Minimum throttle",
            UnitId::Normalized,
            UnitId::Normalized,
            0.0,
            1.0,
            0.0,
            0.01},
        {Px4TecsParameter::MaximumThrottle,
            "FW_THR_MAX",
            "Maximum throttle",
            UnitId::Normalized,
            UnitId::Normalized,
            0.0,
            1.0,
            1.0,
            0.01},
        {Px4TecsParameter::TrimThrottle,
            "FW_THR_TRIM",
            "Trim throttle",
            UnitId::Normalized,
            UnitId::Normalized,
            0.0,
            1.0,
            0.5,
            0.01},
        {Px4TecsParameter::MinimumAirspeed,
            "FW_AIRSPD_MIN",
            "Minimum calibrated airspeed",
            UnitId::MeterPerSecond,
            UnitId::MeterPerSecond,
            5.0,
            100.0,
            25.0,
            0.95},
        {Px4TecsParameter::MaximumAirspeed,
            "FW_AIRSPD_MAX",
            "Maximum calibrated airspeed",
            UnitId::MeterPerSecond,
            UnitId::MeterPerSecond,
            10.0,
            150.0,
            62.0,
            1.4},
        {Px4TecsParameter::MaximumClimbRate,
            "FW_T_CLMB_MAX",
            "Maximum climb rate",
            UnitId::MeterPerSecond,
            UnitId::MeterPerSecond,
            0.1,
            20.0,
            2.5,
            0.199},
        {Px4TecsParameter::MaximumSinkRate,
            "FW_T_SINK_MAX",
            "Maximum sink rate",
            UnitId::MeterPerSecond,
            UnitId::MeterPerSecond,
            0.1,
            20.0,
            2.0,
            0.199},
        {Px4TecsParameter::AltitudeErrorGain,
            "FW_T_HRATE_P",
            "Altitude error gain",
            UnitId::PerSecond,
            UnitId::PerSecond,
            0.001,
            2.0,
            0.10,
            0.01999},
        {Px4TecsParameter::AirspeedErrorGain,
            "FW_T_SPDWEIGHT_P",
            "Airspeed error gain",
            UnitId::PerSecond,
            UnitId::PerSecond,
            0.001,
            2.0,
            0.40,
            0.01999},
        {Px4TecsParameter::ThrottleDampingGain,
            "FW_T_THR_DAMP",
            "Throttle energy-rate damping",
            UnitId::Dimensionless,
            UnitId::Dimensionless,
            0.0,
            3.0,
            0.25,
            0.03},
        {Px4TecsParameter::ThrottleIntegralGain,
            "FW_T_I_GAIN_THR",
            "Throttle integral gain",
            UnitId::PerSecond,
            UnitId::PerSecond,
            0.0,
            2.0,
            0.08,
            0.02},
        {Px4TecsParameter::PitchDampingGain,
            "FW_T_PTCH_DAMP",
            "Pitch energy-balance damping",
            UnitId::Dimensionless,
            UnitId::Dimensionless,
            0.0,
            3.0,
            0.7,
            0.03},
        {Px4TecsParameter::PitchIntegralGain,
            "FW_T_I_GAIN_PIT",
            "Pitch integral gain",
            UnitId::PerSecond,
            UnitId::PerSecond,
            0.0,
            1.0,
            0.03,
            0.01},
        {Px4TecsParameter::EnergyBalanceFeedForwardGain,
            "FW_T_SEB_R_FF",
            "Energy-balance rate feed-forward",
            UnitId::Dimensionless,
            UnitId::Dimensionless,
            0.0,
            2.0,
            1.0,
            0.02},
        {Px4TecsParameter::TotalEnergyRateFilterTimeConstant,
            "FW_T_STE_R_TC",
            "Total-energy rate filter time constant",
            UnitId::Second,
            UnitId::Second,
            0.0,
            5.0,
            0.5,
            0.05},
        {Px4TecsParameter::PitchSlewRate,
            "FW_T_PITCH_RATE",
            "Pitch setpoint slew rate",
            UnitId::RadianPerSecond,
            UnitId::DegreePerSecond,
            math::DegToRad(0.1),
            math::DegToRad(90.0),
            math::DegToRad(8.0),
            math::DegToRad(0.899)},
        {Px4TecsParameter::ThrottleSlewRate,
            "FW_T_THR_SLEW",
            "Throttle slew rate",
            UnitId::PerSecond,
            UnitId::PerSecond,
            0.0,
            10.0,
            0.35,
            0.1},
    }};

constexpr const Px4TecsParameterMetadata &GetPx4TecsParameterMetadata(
    Px4TecsParameter parameter) {
  return GetParameterMetadata(parameter, Px4TecsParameters);
}
} // namespace gnc
